### ISSUE TITLE
Bug on Save when tickbox unchecked

### ISSUE THREAD

**Issue by L1ndaR** [robeastwood/repaircafe.leightonbuzzard.org#45]
When Tickbox for disclaimer not ticked and new repair saved it looks like it has saved but cannot be found in the list.
Would be better to prompt for tick or at least error ?

**Comment by robeastwood** [comment]
Hi @L1ndaR  can you confirm which form you were using when you hit this issue-
Was this when you were checking in at an event, or when you were adding an item yourself to an event in the normal way?

**Comment by robeastwood** [comment]
Thanks. Ok will check it out!

**Comment by robeastwood** [comment]
Cannot replicate on either method to add item.
Closing until more info can be obtained.
