### ISSUE TITLE
Enhancement: Enter Request on Behalf of 

### ISSUE THREAD

**Issue by L1ndaR** [robeastwood/repaircafe.leightonbuzzard.org#46]
unable to change "Owner" when entering a request on behalf of someone.  Is this an admin function ?

**Comment by robeastwood** [comment]
Currently there are two ways to enter new items:

a) A user who has logged into the site can add their own items to an event.
b) An admin, on the day of a repair cafe, can add an item on behalf of a visitor.

Personally, I don't think "standard users" should be able to add items for other users.
Can you explain the use case?

**Comment by robeastwood** [comment]
Yep no probs! That is already possible via the admin check-in functionality.

It should have been sorted at the reception desk on the day ideally. But i think it's been done, it's this item you created on their behalf? https://repaircafe.leightonbuzzard.org/items/98 I can correct the owner if you can let me know who they belong to.

**Comment by L1ndaR** [comment]
its in the Description but looks like you've done it already.    Sunitha?

When we took the shears back they gave us some lawn shears to sharpen. Does that do into event 2 or as a new item for event 3?

**Comment by robeastwood** [comment]
That sounds like a new item, so should have its own new record. Please
encourage them to add it themselves, to the next event.

Cheers

**Comment by L1ndaR** [comment]
it doesn't look like she is in the community but if she registered the shears do you have an email address to send a link to?  I only have a street address and possibly a phone number

**Comment by robeastwood** [comment]
Yes they're registered. I'll email them, but it's up to them to handle this really, there's nothing stopping them from adding any new items.
I'll close this issue as I dont think there's any new functionality required for now.
